bit-sem5/IIS-ITU/src/oafl/browser/urls.py
from . import views
from .converters import SeasonConverter

from django.urls import path, register_converter
from django.contrib.auth.views import LoginView


register_converter(SeasonConverter, 'yyyy-xxxx')

urlpatterns = [
    path('', views.season_redirect, name='season_redirect'),
    path('<yyyy-xxxx:season>/', views.index, name='index'),
    path('<yyyy-xxxx:season>/rozpis/', views.schedule, name='schedule'),
    path('<yyyy-xxxx:season>/vysledky/', views.results, name='results'),
    path('<yyyy-xxxx:season>/tabulka/', views.table, name='table'),
    path('<yyyy-xxxx:season>/tymy/', views.teams, name='teams'),
    path('<yyyy-xxxx:season>/statistiky/', views.stats, name='stats'),
    path('<yyyy-xxxx:season>/play-off/', views.spider, name='play-off'),
    path('registrace-tymu/', views.team_administration, name='team_administration'),
    path('registrace-tymu/prihlaseni/', LoginView.as_view(), name='user_login'),
    path('registrace-tymu/registrace/', views.signup_user, name='user_signup'),
    path('registrace-tymu/odhlaseni/', views.logout_user, name='logout_user'),
    path('registrace-tymu/registrace-hrace/', views.player_registration, name='player_registration'),
    path('registrace-tymu/registrace-tymu/', views.team_registration, name='team_registration'),
    path('registrace-tymu/uprava-tymu/<int:team_id>/', views.team_modify, name='team_modify'),
    path('registrace-tymu/uprava-tymu/<int:team_id>/prejmenovat/', views.team_rename, name='team_rename'),
    path('registrace-tymu/uprava-tymu/<int:team_id>/registrovat_sezonu/', views.register_team_season, name='register_team_season'),
    path('registrace-tymu/uprava-tymu/<int:team_id>/pridat_hrace/', views.add_players_to_team, name='add_players_to_team'),
]

bit-sem5/IIS-ITU/src/oafl/urls.py
from .settings import DEBUG_TOOLBAR

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('oafl.browser.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

bit-sem5/IIS-ITU/src/oafl/browser/models.py
from . import utils

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User


class Team(models.Model):
    name = models.CharField(max_length=50, unique=True)
    user = models.ForeignKey(null=True, on_delete=models.SET_NULL, to=User)

    def __str__(self):
        return self.name


class Season(models.Model):
    begin_date = models.DateField(unique=True, null=True)
    end_date = models.DateField(unique=True, null=True)
    teams = models.ManyToManyField(Team, through='SeasonTeam')

    def __str__(self):
        return '{}-{}'.format(self.begin_date.year, self.end_date.year)

    def is_current(self):
        return self == utils.get_current_season()


class SeasonTeam(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    final_place = models.PositiveSmallIntegerField(null=True, blank=True)
    registered = models.BooleanField(default=False)

    class Meta:
        unique_together = ('team', 'season')
        verbose_name = 'Team'
        verbose_name_plural = 'Teams'

    def __str__(self):
        return '{} ({})'.format(self.team, self.season)


class Round(models.Model):
    GROUP_PHASE = 'GP'
    EIGHT_FINAL = 'EF'
    QUATERFINAL = 'QF'
    SEMIFINAL = 'SF'
    FINAL = 'F'
    TYPE_CHOICES = (
        (GROUP_PHASE, 'Group phase'),
        (EIGHT_FINAL, 'Eight-final'),
        (QUATERFINAL, 'Quaterfinal'),
        (SEMIFINAL, 'Semifinal'),
        (FINAL, 'Final')
    )

    number = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(999)], null=True)
    type = models.CharField(max_length=2, choices=TYPE_CHOICES, null=True)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('number', 'season')

    def __str__(self):
        return '{}. round in {}'.format(self.number, self.season)


class Player(models.Model):
    GOALKEEPER = "G"
    DEFENDER = "D"
    ATTACKER = "A"
    POSITION_CHOICES = (
        (GOALKEEPER, 'Goalkeeper'),
        (DEFENDER, 'Defender'),
        (ATTACKER, 'Attacker'),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField()
    position = models.CharField(max_length=1, choices=POSITION_CHOICES, null=True)
    dress_number = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(99)])
    team_season = models.ManyToManyField(SeasonTeam, related_name='teams')

    # ToDo:
    # class Meta:
    #     unique_together = ('dress_number', 'team_season')

    def __str__(self):
        return '{} {}'.format(self.last_name, self.first_name)


class Match(models.Model):
    number = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(9999)], null=True)
    date_time = models.DateTimeField(unique=True, null=True)
    played = models.BooleanField(default=False)
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='match_home_team')
    away_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='match_away_team')
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    home_team_players = models.ManyToManyField(Player, related_name='home_team_players')
    away_team_players = models.ManyToManyField(Player, related_name='away_team_players')

    class Meta:
        verbose_name_plural = "Matches"

    def __str__(self):
        return '{}-{} | {} vs {}'.format(self.number, self.round.season, self.home_team, self.away_team)


class Goal(models.Model):
    time = models.TimeField()
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    assist_player = models.ForeignKey(Player, on_delete=models.CASCADE, null=True, blank=True,
                                      related_name='goal_assist_player')
    score_player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='goal_score_player')
    collect_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='goal_collect_team')
    score_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='goal_score_team')

    def __str__(self):
        return '{} ({}, {}) scores to {}'.format(self.score_team, self.score_player, self.assist_player,
                                                 self.collect_team)


class Penalty(models.Model):
    SHORT_PENALTY = 2
    LONG_PENALTY = 5
    LENGTH_CHOICES = (
        (SHORT_PENALTY, '2 minutes'),
        (LONG_PENALTY, '5 minutes'),
    )

    length = models.PositiveSmallIntegerField(choices=LENGTH_CHOICES, null=True)
    time = models.TimeField()
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Penalties"

    def __str__(self):
        return '{} - {} minutes penalty in {}'.format(self.player, self.length, self.match)

bit-sem5/IIS-ITU/src/oafl/browser/views.py
from . import models
from .utils import set_current_season, get_current_season, team_modify_authenticate, add_players_to_team_util
from . import forms

from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Sum
from django.contrib.auth import login, authenticate, logout
from django.http import Http404

from collections import defaultdict
from datetime import date


def season_redirect(request):
    latest_season = models.Season.objects.latest('begin_date')
    selected_season = request.session.get('selected_season', str(latest_season))
    request.session['selected_season'] = str(selected_season)
    return redirect('index', season=str(selected_season))


def index(request, season):
    set_current_season(season, request)
    return render(request, 'browser/index.html', {'current_season': season})


def schedule(request, season):
    set_current_season(season, request)
    data = []
    rounds = models.Round.objects.filter(season__exact=season)

    for rnd in rounds:
        inner_data = []
        matches = models.Match.objects.filter(round__exact=rnd)
        if matches.count() == 0:
            continue

        for match in matches:
            inner_data.append({'number': match.number, 'date_time': match.date_time, 'played': match.played,
                               'home_team': match.home_team, 'away_team': match.away_team})

        inner_data = sorted(inner_data, key=lambda m: m['number'])
        data.append({'number': rnd.number, 'type': rnd.type, 'matches': inner_data})

    data = sorted(data, key=lambda r: r['number'])

    page = request.GET.get('page', 1)
    paginator = Paginator(data, 1)

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    return render(request, 'browser/schedule.html', {'data': data})


def results(request, season):
    set_current_season(season, request)
    data = []
    rounds = models.Round.objects.filter(season__exact=season)

    for rnd in rounds:
        inner_data = []
        matches = models.Match.objects.filter(round__exact=rnd, played__exact=True)
        if matches.count() == 0:
            continue

        for match in matches:
            goals = models.Goal.objects.filter(match__exact=match)
            penalties = models.Penalty.objects.filter(match__exact=match)

            home_team_events = []
            away_team_events = []
            home_team_goals = 0
            away_team_goals = 0

            for goal in goals:
                if goal.score_team_id == match.home_team_id:
                    home_team_events.append({'time': goal.time, 'type': 'goal', 'score_player': goal.score_player,
                                             'assist_player': goal.assist_player})
                    home_team_goals += 1
                elif goal.score_team_id == match.away_team_id:
                    away_team_events.append({'time': goal.time, 'type': 'goal', 'score_player': goal.score_player,
                                             'assist_player': goal.assist_player})
                    away_team_goals += 1

            for penalty in penalties:
                if penalty.player_id in match.home_team_players.all().values('id').values_list('id', flat=True):
                    home_team_events.append({'time': penalty.time, 'type': 'penalty', 'length': penalty.length,
                                             'player': penalty.player})
                elif penalty.player_id in match.away_team_players.all().values('id').values_list('id', flat=True):
                    away_team_events.append({'time': penalty.time, 'type': 'penalty', 'length': penalty.length,
                                             'player': penalty.player})

            home_team_events = sorted(home_team_events, key=lambda e: e['time'])
            away_team_events = sorted(away_team_events, key=lambda e: e['time'])

            inner_data.append({'number': match.number, 'date_time': match.date_time, 'played': match.played,
                               'home_team': match.home_team, 'away_team': match.away_team,
                               'home_team_goals': home_team_goals, 'away_team_goals': away_team_goals,
                               'home_team_events': home_team_events, 'away_team_events': away_team_events})

        inner_data = sorted(inner_data, key=lambda m: m['number'])
        data.append({'number': rnd.number, 'type': rnd.type, 'matches': inner_data})

    data = sorted(data, key=lambda r: r['number'])

    page = request.GET.get('page', 1)
    paginator = Paginator(data, 1)

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    return render(request, 'browser/results.html', {'data': data})


def table(request, season):
    set_current_season(season, request)
    data = []
    matches = models.Match.objects.filter(round__season__exact=season, played__exact=True)
    teams = season.teams.all()

    for team in teams:
        matches_cnt = 0
        wins_cnt = 0
        draws_cnt = 0
        loses_cnt = 0
        scored_goals_cnt = 0
        collect_goals_cnt = 0
        points_cnt = 0

        for match in matches:
            if team.id == match.home_team_id or team.id == match.away_team_id:
                matches_cnt += 1
                goals = models.Goal.objects.filter(match__exact=match)
                scored_goals_this_match_cnt = 0
                collect_goals_this_match_cnt = 0

                for goal in goals:
                    if goal.score_team_id == team.id:
                        scored_goals_this_match_cnt += 1
                    elif goal.collect_team_id == team.id:
                        collect_goals_this_match_cnt += 1

                if scored_goals_this_match_cnt > collect_goals_this_match_cnt:
                    wins_cnt += 1
                    points_cnt += 3
                elif scored_goals_this_match_cnt < collect_goals_this_match_cnt:
                    loses_cnt += 1
                else:
                    draws_cnt += 1
                    points_cnt += 1

                scored_goals_cnt += scored_goals_this_match_cnt
                collect_goals_cnt += collect_goals_this_match_cnt

        data.append({'team_name': team.name, 'matches': matches_cnt, 'wins': wins_cnt, 'draws': draws_cnt,
                     'loses': loses_cnt, 'scored_goals': scored_goals_cnt, 'collect_goals': collect_goals_cnt,
                     'diff_goals': scored_goals_cnt - collect_goals_cnt, 'points': points_cnt})

    data = sorted(data, key=lambda t: (t['points'], t['diff_goals'], t['scored_goals']), reverse=True)

    return render(request, 'browser/table.html', {'data': data})


def teams(request, season):
    set_current_season(season, request)
    data = {"teams": []}

    for team in season.teams.all():
        seasons_played = models.Season.objects.filter(teams=team, begin_date__lt=season.begin_date).count()
        if date.today() > season.end_date:
            seasons_played += 1
        seasons_team = models.SeasonTeam.objects.filter(team=team) \
                                                .exclude(final_place=0) \
                                                .filter(season__end_date__lte=date.today()) \
                                                .order_by('final_place')
        best_place = seasons_team.first().final_place\
            if seasons_team.count() > 0 and seasons_team.first().final_place is not None\
            else "N/A"
        season_team = models.SeasonTeam.objects.get(season=season, team=team)
        players = models.Player.objects.filter(team_season=season_team)

        if players.count() == 0:
            # ignore empty teams
            continue

        data["teams"].append({
            "name": team.name,
            "players": players,
            "seasons_played": seasons_played,
            "best_place": best_place
        })

    return render(request, 'browser/teams.html', data)


def stats(request, season):
    set_current_season(season, request)
    data = {"players": []}
    for player in models.Player.objects.all():
        if player.team_season.filter(season=season).count() == 0:
            continue  # skip players that did not play selected season
        goals_count = models.Goal.objects.filter(score_player=player, match__round__season=season).count()
        assists = models.Goal.objects.filter(assist_player=player ,match__round__season=season).count()
        penalty_minutes = models.Penalty.objects.filter(player=player, match__round__season=season).aggregate(Sum("length"))["length__sum"]
        played_matches = models.Match.objects.filter(played=True, round__season=season)
        data["players"].append({
            "name": player,
            "team": player.team_season.get(season=season).team,
            "goals": goals_count,
            "assists": assists,
            "matches": played_matches.filter(home_team_players=player).count() +
                       played_matches.filter(away_team_players=player).count(),
            "penalty_minutes": penalty_minutes if penalty_minutes is not None else 0,
            "points": goals_count + assists
        })

    data["players"].sort(key=lambda x: x["points"], reverse=True)
    for i, player in enumerate(data["players"], 1):
        player["rank"] = i

    page = request.GET.get('page', 1)
    paginator = Paginator(data["players"], 20)

    try:
        data["players"] = paginator.page(page)
    except PageNotAnInteger:
        data["players"] = paginator.page(1)
    except EmptyPage:
        data["players"] = paginator.page(paginator.num_pages)

    return render(request, 'browser/stats.html', data)


def spider(request, season):

bit-sem5/IIS-ITU/src/templates/browser/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="center-block">

    <h3>Kdo jsme</h3>
    <p>
        Jsme amatérská florbalová soutěž, která funguje již od roku 2010. Organizují a hrají ji především
        florbalový nadšenci, nikoliv profesionální sportovci. Liga se hraje od podzimu do jara, přes léto
        si dáváme pauzu. Hrajeme v nové víceúčelové hale v obci Dolní Dobrouč. Ta se nachází v podhoří
        Orlických hor na východě Pardubického kraje. V hale jsou dvě šatny a tribuna pro fanoušky. Kolem haly
        se nachází parkoviště, je tedy možné zaparkovat auto.
    </p>

    <div class="row image-row">
        <div class="col-md-4">
            <img src="{% static "images/hala_venek.jpg" %}" alt="Víceúčelová hala Dolní Dobrouč 1"
                 class="responsive-image">
        </div>
        <div class="col-md-4">
            <img src="{% static "images/hala_vnitrek.jpg" %}" alt="Víceúčelová hala Dolní Dobrouč 2"
                class="responsive-image">
        </div>
        <div class="col-md-4">
            <img src="{% static "images/hala_satny.jpg" %}" alt="Víceúčelová hala Dolní Dobrouč 3"
                class="responsive-image">
        </div>
    </div>

    <h3>Jak se příhlásit</h3>
    <p>
        Pokud chcete ligu hrát a máte tým můžete využít našeho webového rozhraní k registraci. Zaregistrujete se,
        zaplatíte registrační poplatek pro sezónu, ten činí 10000 KČ za tým. Po uhrazení si budete moci vytvořit
        tým, napsat soupisku hráčů (až 17 lidí) a přihlásit tým do nadcházející seźony. Pochopitelně není možné
        přihlásit tým do již rozběhnuté sezóny. Startovné jde z drtivé části na zaplacení haly, zbytek se dává
        rozhodčím. Soupiska hráčů je závažná a až na výjimky ji není možné během sezóny měnit. Při porušení
        tohoto pravidla, jsou zápasy, kde bude toto porušení prokázáno, diskvalifikovány v neprospěch provinilého
        týmu. Při opakovaném porušení, hrozí vyloučení z ligy bez možnosti vrácení startovného.
    </p>

    <div class="row image-row">
        <div class="col-md-4">
            <img src="{% static "images/hra_1.jpg" %}" alt="Hra 1"
                 class="responsive-image">
        </div>
        <div class="col-md-4">
            <img src="{% static "images/hra_2.jpg" %}" alt="Hra 2"
                class="responsive-image">
        </div>
        <div class="col-md-4">
            <img src="{% static "images/hra_3.jpg" %}" alt="Hra 3"
                class="responsive-image">
        </div>
    </div>

    <h3>Pravidla</h3>
    <p>Hrajeme, až na změny uvedené níže, podle oficiálních pravidel florbalu od IFF -
        <a href="https://floorball.sport/">
            International Florbal Federation
        </a>
        . Originál je možné najít zde -
        <a href="http://www.floorball.org/Liitetiedostot/Regulations/2018/Rules%20of%20the%20Game%20Edition%202018.pdf">
            International Floorball Federation, Rules and Competition Committee
        </a>
        . Výklad a překlad pravidel do Češtiny tady -
        <a href="https://media.ceskyflorbal.cz/media/dms/89/89b8d384-63c7-48a1-9d57-6317e6231dab.pdf">
            Český florbal, Pravidla florbalu (Edice 2018)
        </a>
        . Změna je v hrací době, kdy hrajeme pouze na dvě třetiny hrubého času. Tedy 2x 20 minut. Časomíra
        se zastavuje pouze při vstřeleném gólu, vyloučení, nebo mimořádných událostech, například zranění.
        Liga je také smíšená, v týmu mohou být tedy i ženy. Hráči musí být starší 15ti let, horní hranice
        není. V týmu mohou být maximálně tři registrování hráči pod českou florbalovou asociací, jsme liga
        amatérská.
    </p>

    <div class="row image-row">
        <div class="col-md-4">
            <img src="{% static "images/hra_4.jpg" %}" alt="Hra 4"
                 class="responsive-image">
        </div>
        <div class="col-md-4">
            <img src="{% static "images/hra_5.jpg" %}" alt="Hra 5"
                class="responsive-image">
        </div>
        <div class="col-md-4">
            <img src="{% static "images/hra_6.jpg" %}" alt="Hra 6"
                class="responsive-image">
        </div>
    </div>

    <h3>Herní systém</h3>
    <p>
        Sezóna je rozdělena na dvě části, základní a vyřazovací. V základní části se utká každý tým s každým
        2x. Jednou jako domácí, jednou jako host. Hrací kola jsou obvykle o víkendech, v průměru jednou za 14 dní
        a obvykle se hraje celý den, od rána do večera. Do vyřazovací fáze pak postupuje prvních 8 týmů z tabulky.
        Ve čtvrtfinále se spolu utká první s osmým, druhý se sedmým a podobně. Hraje se na dva vítězné zápasy.
        Vítězové se spolu utkají v semifinále stejným systémem a nakonec vítězové semifinálových duelů ve finále
        o první misto. Zápas o třetí místo není. Zbývající pořadí určuje pořadí ze základním části. Zároveň je
        oceněn nejlepší střelec, hráč s nejvíce asistencemi, nejproduktivnější hráč a nejlepší gólman sezóny.
        Do těchto statistik se počítají zápasy ze základní i vyřazovací části.
    </p>

    <h3>Víceúčelová hala Dolní Dobrouč</h3>
    <div class="mt-1 mb-2 image-row" id="oafl-map"></div>
    <br>

</div>

<script src="{% static 'js/map.js' %}">
</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDjy50t8IKx1u6Pwo2I6vdtX26W7RgBZPI&callback=initMap">
</script>

<script>
    $(document).ready(function () {
        $(".nav ul li").removeClass("active");
        $('#home').addClass('active');
    });
</script>

{% endblock %}

bit-sem5/IIS-ITU/src/templates/browser/spider.html
{% extends "base.html" %}
{% load static %}

{% block add-header %}
    <link rel="stylesheet" href="{% static "css/spider.css" %}">
{% endblock %}

{% block content %}
    {% if not QF %}
        <h4>Zatím nejsou dostupné žádné zápasy v play-off</h4>
    {% else %}
        <div class="row">
            <div class="col-md-4 text-center">
                <h3>Čtvrtfinále</h3>
            </div>
            <div class="col-md-4 text-center">
                <h3>Semifinále</h3>
            </div>
            <div class="col-md-4 text-center">
                <h3>Finále</h3>
            </div>
        </div>
    {% endif %}
    <div class="row spider">
        <div class="col-md-4">
            {% for result in QF %}
                {% include "browser/includes/spider_result.html" with result=result%}
            {% endfor %}
        </div>
        <div class="col-md-4 semi-final">
            {% for result in SF %}
                {% include "browser/includes/spider_result.html" with result=result%}
            {% endfor %}
        </div>
        <div class="col-md-4 final">
            {% for result in final %}
                {% include "browser/includes/spider_result.html" with result=result%}
            {% endfor %}
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $(".nav ul li").removeClass("active");
            $('#spider').addClass('active');
        });
    </script>
{% endblock %}

bit-sem5/IIS-ITU/src/templates/browser/team_modify.html
{% extends "base.html" %}
{% load static %}

{% block add-header %}
    <link rel="stylesheet" href="{% static "css/team_modify.css" %}">
{% endblock %}

{% block content %}
    <div class="row team-modify">
        <div class="col-md-12 text-center">
            <h2>Tým {{ team.name }}</h2>
            <button type="button" class="btn btn-defaults" data-toggle="modal" data-target="#exampleModal">
                Přejmenovat
            </button>
        </div>
        <div class="col-md-6 text-center">
            {% for season in seasons_data %}
                {% if season.played %}
                    <h3>
                        {{ season.title }}
                    </h3>
                    <div class="row">
                        <div class="col-md-12">
                            {% if  season.registered %}
                                <h5 class="inline">Hráči:</h5>
                                {% for player in season.players %}
                                    <div class="team-modify-player">{{ player }}</div>
                                {% endfor %}
                            {% else %}
                                Tým není zaregistrován
                            {% endif %}
                        </div>
                    </div>

                    {% if season.current %}
                        <hr>
                        <h2>Historie</h2>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
        <div class="col-md-6 text-center">
            <h2>Registrace týmu na sezónu</h2>
            {% if current_season %}

                <div class="row">
                <div class="col-md-6">
                    {% for player in current_season.players %}
                        <div class="team-modify-player">{{ player }}
                            {# players can be removed only before the seasons starts #}
                            <i class="fa fa-times" data-player-id="{{ player.id }}"></i>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-md-6">
                    <div>
                        <input type="text" id="player_search" name="search" style="margin: 10px;width: 165px;"
                               onkeyup="filter()">
                    </div>
                    <div>
                        <select id="player_select" size="10" style="margin: 10px; width: 165px;height: 170px;">
                            {% for player in players_to_add %}
                                <option class="add-player" data-player-id="{{ player.id }}">{{ player }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <h6>Poklikejte na hráče pro přidání</h6>
                </div>
                <div class="col-md-12">
                {% if current_season.registered %}
                    Tým je zaregistrován do aktuání sezóny
                {% else %}
                    <button class="btn btn-default register-team" data-season-id="{{ current_season.id }}">Registrovat
                    </button>
                {% endif %}
                <br>
                <br>
            {% else %}
                <br>
                <h4>Žádná sezóna není otevřena pro registraci</h4>
            {% endif %}
            </div>

            </div>

        </div>
    </div>

    <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    <form action="{% url "team_rename" team.id %}" method="post">
                        {% include "browser/includes/form.html" with form=team_form %}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zavřít</button>
                        <button type="submit" class="btn btn-primary">Přejmenovat</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {# this form is submitted by js #}
    <form class="hidden" id="register-season-form" action="{% url "register_team_season" team.id %}" method="post">
        {% include "browser/includes/form.html" with form=season_team_form %}
    </form>
{% endblock %}

{% block scripts %}
    <script>
        function filter() {
            var keyword = document.getElementById("player_search").value;
            let select = document.getElementById("player_select");
            for (let i = 0; i < select.length; i++) {
                let txt = select.options[i].text;
                if (txt.substring(0, keyword.length).toLowerCase() !== keyword.toLowerCase() && keyword.trim() !== "") {
                    $(select.options[i]).attr('disabled', 'disabled').hide();
                } else {
                    $(select.options[i]).removeAttr('disabled').show();
                }
            }
        }

        function add_players(players_arr, remove) {
            let post_data = {
                players: players_arr,
                csrfmiddlewaretoken: $("[name=csrfmiddlewaretoken]").val()
            };

            if (remove) {
                post_data["remove"] = true;
            }

            $.ajax({
                type: 'POST',
                url: "{% url "add_players_to_team" team.id %}",
                data: post_data,
                async: false
            });

            window.location.reload();
        }

        $(document).ready(function () {
            $(".add-player").dblclick(function () {
                let player_id = $(this).attr("data-player-id");
                add_players([player_id], false);
            });

            $(".btn.register-team").click(function () {
                $("select#id_season").val($(this).attr("data-season-id"));
                $("select#id_team").val({{ team.id }});
                $("#register-season-form").submit();
            });

            $(".team-modify-player i").click(function () {
                let player_id = $(this).attr("data-player-id");
                add_players([player_id], true);
            })
        });

    </script>
{% endblock %}